#!/usr/bin/env bash
#
# Prepares photos for the /gallery page.
#
#   scripts/prepare-gallery-images.sh <source-folder> [output-root]
#
# For every image in <source-folder> this writes two optimized JPEGs:
#   public/gallery/full/<slug>.jpg    longest edge 1920px, for the full-screen view
#   public/gallery/thumb/<slug>.jpg   longest edge 800px, for the grid tiles
#
# This site is a static export with `images: { unoptimized: true }`, so whatever
# lands in public/ is what visitors download. Nothing resizes at build time.
#
# The slug comes from the source filename, so rename source files to something
# meaningful (e.g. volleyball-studio-portrait.heic) before running this.
#
# Rotation is baked in rather than left to an EXIF flag, so the printed aspect
# ratio always matches what a browser will render.

set -euo pipefail

SOURCE_DIR="${1:?usage: scripts/prepare-gallery-images.sh <source-folder> [output-root]}"
OUTPUT_ROOT="${2:-public/gallery}"

FULL_MAX_EDGE=1920
THUMB_MAX_EDGE=800
FULL_QUALITY=4   # ffmpeg -q:v, roughly 80% JPEG quality
THUMB_QUALITY=5

for tool in ffmpeg ffprobe; do
  command -v "$tool" >/dev/null 2>&1 || { echo "error: $tool is required (brew install ffmpeg)" >&2; exit 1; }
done

mkdir -p "$OUTPUT_ROOT/full" "$OUTPUT_ROOT/thumb"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

slugify() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//'
}

resize() {
  local input="$1" output="$2" max_edge="$3" quality="$4"
  ffmpeg -loglevel error -y -i "$input" \
    -vf "scale=w='min(${max_edge},iw)':h='min(${max_edge},ih)':force_original_aspect_ratio=decrease:flags=lanczos" \
    -q:v "$quality" "$output"
}

echo "// Generated by scripts/prepare-gallery-images.sh; fill in category, alt, and caption."
count=0

for source in "$SOURCE_DIR"/*; do
  [ -f "$source" ] || continue

  filename="$(basename "$source")"
  extension="$(printf '%s' "${filename##*.}" | tr '[:upper:]' '[:lower:]')"
  case "$extension" in
    jpg|jpeg|png|heic|heif|webp|tif|tiff) ;;
    *) continue ;;
  esac

  slug="$(slugify "${filename%.*}")"
  decoded="$source"

  # ffmpeg cannot decode HEIC, so hand that step to macOS.
  if [ "$extension" = "heic" ] || [ "$extension" = "heif" ]; then
    command -v sips >/dev/null 2>&1 || { echo "error: sips is required to decode $filename" >&2; exit 1; }
    decoded="$TMP_DIR/$slug.jpg"
    sips -s format jpeg -s formatOptions best "$source" --out "$decoded" >/dev/null
  fi

  resize "$decoded" "$OUTPUT_ROOT/full/$slug.jpg" "$FULL_MAX_EDGE" "$FULL_QUALITY"
  resize "$decoded" "$OUTPUT_ROOT/thumb/$slug.jpg" "$THUMB_MAX_EDGE" "$THUMB_QUALITY"

  dimensions="$(ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=p=0 "$OUTPUT_ROOT/full/$slug.jpg")"
  width="${dimensions%%,*}"
  height="${dimensions##*,}"
  aspect_ratio="$(awk -v w="$width" -v h="$height" 'BEGIN { printf "%.4f", w / h }')"

  printf '  { slug: "%s", category: "TODO", thumbSrc: "/gallery/thumb/%s.jpg", fullSrc: "/gallery/full/%s.jpg", alt: "TODO", aspectRatio: %s },\n' \
    "$slug" "$slug" "$slug" "$aspect_ratio"
  count=$((count + 1))
done

echo "// $count photo(s) prepared. Folder size: $(du -sh "$OUTPUT_ROOT" | cut -f1)" >&2
